### ISSUE TITLE
Steal the Mu misID unfolding code from Zishuo/Phoebe's run 2 R(J/psi) analysis

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/misid-unfold#1]
ZIshuo and Phoebe has implemented something very similar. We should see how much we can steal.

FYI @manuelfs

**Comment by manuelfs** [comment]
Which code from the R(J/psi) analysis do you want to steal?

**Comment by yipengsun** [comment]
Updated title to reflect that we only want the `Mu` misID unfolding part :)

**Comment by yipengsun** [comment]
Zishuo has committed his misID unfolding code in the project root. I've talked w/ Zishuo yesterday for an overview, and I'm still not fully clear on this. I'll provide a big-picture review in a different issue on next Tue after understanding it better.
