### ISSUE TITLE
Implement misID unfolding based on Zishuo's code

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/misid-unfold#2]
## Implementation status

- [x] Apply tag cuts to fake line real data (misID samples) (2016, both polarities)
- [x] Obtain `true -> tag` efficiencies from `pidcalib`
    - This doesn't cover the ghost samples
    - For ghost, we use Zishuo's sample for now
- [x] Compute true yields (unfolded yields)
- [x] Compute the weights required for misID
- [x] Apply these weights to misID samples

The other remaining issues:

- Find a Ghost MC sample
- Apply momentum smearing

will be tracked in separate issues.

## Output

- Before unfolding:

    ![D0_tag_eta](https://user-images.githubusercontent.com/33738176/160956998-ca1168a7-2576-4be7-9099-dddcac08d7f1.png)
    
    ![D0_tag_p](https://user-images.githubusercontent.com/33738176/160960011-7733b19a-68fb-43dc-932a-f013cfa9d30d.png)

- After unfolding:

    ![D0_true_eta](https://user-images.githubusercontent.com/33738176/160957032-d7e18265-b43f-4cbc-a160-c47a111e3d5d.png)

    ![D0_true_p](https://user-images.githubusercontent.com/33738176/160960059-c8096a33-4faa-4ace-bb96-7ebf6e9ff84c.png)

## Problems (group meeting)

1. We are using Phoebe's run 1 cuts, and some of the tagged species (`K, p`) have very low stat:

    ![misid_tag_cuts](https://user-images.githubusercontent.com/33738176/160956180-38de3838-b809-4823-8f2a-4b061a67475f.png)

    Any suggestions on which cuts are more important to tweak?

2. More info for the previous point:

    `K, p` are empty in bin `1, 1, 1`:
    https://github.com/umd-lhcb/misid-unfold/blob/219802ebd1e451691739eafa1f2cc0b76b9d2d23/histos/rdx-22_03_30_12_40-unfolded-2016/stdout.log#L181-L183

    Also, lots of 0 efficiencies for the same bin:
    https://github.com/umd-lhcb/misid-unfold/blob/219802ebd1e451691739eafa1f2cc0b76b9d2d23/histos/rdx-22_03_30_12_40-unfolded-2016/stdout.log#L187-L192
    
    [resp_mat.pdf](https://github.com/umd-lhcb/misid-unfold/files/8385769/resp_mat.pdf)

3. We used Beysian unfolding (iterative unfolding). Both Jack and Zishuo use the default number of iteration of 4. For me, in order to get a `chi2` that is ~ const, the iteration needs to be set to 20! Any thoughts on this?

## Questions (offline)

1. Should we apply mass window cuts to the misID samples?
    - Probably yes, but just want to be sure
    - We need to unfold nominal region and USB separately

2. If the first point is true, should we do a separate unfolding for the USB?
    - Yes

4. Should we do 1 unfolding per tree (e.g. `D*, D0, D* ws Pi, D* ws Mu, D0 ws`), or `D*, D0`, or just a single tree and use it on all samples?
    - Yes

6. When compute `tag -> true` from `true -> tag`, we need 2 prior probabilities: `true`, `tag`. For `tag`, can I just use the yield fraction directly, or should I rewrite it as `tag = sum(tag -> true, true)`, as the ANA implies?
    - Use the sum here, because it's more consistent.

8. Ask Greg about the Ghost MC sample he provided to RD+

**Comment by yipengsun** [comment]
Here's the gist of unfolding (comments are mine):

```cpp

          TH1D *measured_hist, *response_truth;
          TH2D *response_hist;

            for (int row = 0; row < numClasses; row++) {
              measured_hist->SetBinContent(row + 1, measured_vector[row]);
              response_truth->SetBinContent(row + 1, 1); // the true response are just vectors of 1, probably just used for dimension
              for (int col = 0; col < numClasses; col++) {
                response_hist->SetBinContent(row + 1, col + 1,
                                             response_matrix[row][col]);
                if (verbose)
                  std::cout << std::setw(10) << std::setprecision(4)
                            << response_hist->GetBinContent(row + 1, col + 1)
                            << " | ";
              }
              if (verbose)
                std::cout << std::endl;
            }

            RooUnfoldResponse response(0, response_truth, response_hist); // 0 actually represents a nullptr
            int numIters = 4;
            RooUnfoldBayes unfold(&response, measured_hist, numIters);
            TH1D *reco = static_cast<TH1D *>(unfold.Hreco());
```

**Comment by yipengsun** [comment]
Zishuo used a coarse binning:

```
File: myPid.root, Histo: H2H_Ghost_TO_P
Slicing axis: η

## η, 1 (1.7,3.6)
+-------------------+---------------+-------------+
|     p \ nTrk      | 1 (0.0,200.0) |  2 (600.0)  |
+-------------------+---------------+-------------+
| 1 (3000.0,6000.0) |  0.00 ± 0.00  | 0.00 ± 0.00 |
|    2 (10000.0)    |  0.00 ± 0.00  | 0.00 ± 0.00 |
|    3 (15600.0)    |  0.01 ± 0.00  | 0.00 ± 0.00 |
|    4 (27000.0)    |  0.03 ± 0.00  | 0.02 ± 0.00 |
|    5 (60000.0)    |  0.04 ± 0.00  | 0.02 ± 0.00 |
|   6 (100000.0)    |  0.02 ± 0.00  | 0.01 ± 0.00 |
+-------------------+---------------+-------------+

## η, 2 (5.0)
+-------------------+---------------+-------------+
|     p \ nTrk      | 1 (0.0,200.0) |  2 (600.0)  |
+-------------------+---------------+-------------+
| 1 (3000.0,6000.0) |  0.00 ± 0.00  | 0.00 ± 0.00 |
|    2 (10000.0)    |  0.00 ± 0.00  | 0.00 ± 0.00 |
|    3 (15600.0)    |  0.00 ± 0.00  | 0.00 ± 0.00 |
|    4 (27000.0)    |  0.01 ± 0.00  | 0.01 ± 0.00 |
|    5 (60000.0)    |  0.03 ± 0.00  | 0.02 ± 0.00 |
|   6 (100000.0)    |  0.04 ± 0.00  | 0.02 ± 0.00 |
+-------------------+---------------+-------------+
```

For now we need to use the same binning scheme, because we are using Zishuo's Ghost histograms.

**Comment by yipengsun** [comment]
Zishuo's momentum cut is identical to RDX run 1:

```cpp
      IN_RANGE(mu_p, 3.0e3, 100.0e3) &&
```

So the histograms should be fine for a pilot run.

**Comment by yipengsun** [comment]
Trying to make `pidcalib2` work, I got the following error:

```

  File "/cvmfs/lhcbdev.cern.ch/conda/envs/pidcalib/2022-02-11_22-35/linux-64/bin/pidcalib2.make_eff_hists", line 10, in <module>
    sys.exit(main())
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/pidcalib/2022-02-11_22-35/linux-64/lib/python3.9/site-packages/pidcalib2/make_eff_hists.py", line 228, in main
    make_eff_hists(config)
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/pidcalib/2022-02-11_22-35/linux-64/lib/python3.9/site-packages/pidcalib2/make_eff_hists.py", line 218, in make_eff_hists
    with open(eff_hist_path, "wb") as f:
OSError: [Errno 36] File name too long: 'raw_histos/piTrue-16/effhists-Turbo16-down-Pi-IsMuon==0.0&InMuonAcc==1.0&(MC15TuneV1_ProbNNpi>0.1&DLLK<0.0&DLLp<0.0&DLLe<2.0&MC15TuneV1_ProbNNghost<0.25==0)&(DLLK>0.0&DLLp<0.0&(DLLe-DLLK)<-2.0&MC15TuneV1_ProbNNghost<0.25==0)&(DLLp>2.0&DLLK<0.0&(DLLe-DLLp)<-2.0&MC15TuneV1_ProbNNghost<0.25==0)&(DLLe>2.0&(DLLe-DLLK)>-2.0&(DLLe-DLLp)>-2.0&MC15TuneV1_ProbNNghost<0.25==0)-Brunel_P.Brunel_ETA.nTracks_Brunel.pkl'
```

It is very annoying that `pidcalib2` generates filenames automatically and the name can be too long!

**Comment by yipengsun** [comment]
@afernez @manuelfs I've summarized the misID unfolding situation in the top post. Please take a look and see if it's clear.

**Comment by yipengsun** [comment]
@afernez Response matrix (pdf version) added.

**Comment by yipengsun** [comment]
I think I know why the Muon tag has 0 efficiency. Taking a look at the output:

```
[I 220406 23:51:07 utils:517] Processed 3/3 files
[I 220406 23:51:07 utils:596] 1084608/1173971 (92.4%) events passed binning range cut
[I 220406 23:51:07 utils:596] 1007591/1084608 (92.9%) events passed user cut
[I 220406 23:51:07 utils:596] 819720/1007591 (81.4%) events passed 'MC15TuneV1_ProbNNpi>0.1&DLLK<0.0&DLLp<0.0&DLLe<2.0&MC15TuneV1_ProbNNghost<0.25' cut
[I 220406 23:51:07 utils:596] 0/1007591 (0.0%) events passed 'IsMuon==1.0&DLLmu>2.0&DLLe<1.0' cut
[I 220406 23:51:07 utils:596] 1007591/1007591 (100.0%) events passed 'IsMuon==0.0&InMuonAcc==1.0' cut
[D 220406 23:51:07 utils:93] Created 'eff_MC15TuneV1_ProbNNpi>0.1&DLLK<0.0&DLLp<0.0&DLLe<2.0&MC15TuneV1_ProbNNghost<0.25' histogram
[D 220406 23:51:07 utils:93] Created 'eff_IsMuon==1.0&DLLmu>2.0&DLLe<1.0' histogram
```

The problem is: I had a mis-understanding of the `--cut` vs `--pid-cut` flags

I thought the procedure would be:

- For each `cut, pid_cut` pair, apply `cut`, then `pid_cut`, compute efficiency

What actually happened is:

- `--cut` can be supplied multiple times. Denote each element `c`
- Apply all `c`
- Apply cuts supplied in the multiple `--pid-cut` flag.

**Comment by yipengsun** [comment]
Now the `h -> muTag` efficiencies and `h -> fake` efficiencies are no longer consistently 0, and 1:

## `p -> muTag`

These are still very small.

### η, 1 (1.7,3.6)
| p \ nTrk          | 1 (0.0,200.0)      | 2 (600.0)          |
|-------------------|--------------------|--------------------|
| 1 (3000.0,6000.0) | 0.00623 ± 0.00243  | -0.00110 ± 0.00640 |
| 2 (10000.0)       | -0.00066 ± 0.00144 | 0.00501 ± 0.00346  |
| 3 (15600.0)       | -0.00032 ± 0.00104 | 0.00099 ± 0.00240  |
| 4 (27000.0)       | 0.00129 ± 0.00077  | 0.00194 ± 0.00157  |
| 5 (60000.0)       | 0.00061 ± 0.00052  | 0.00215 ± 0.00115  |
| 6 (100000.0)      | -0.00064 ± 0.00069 | 0.00346 ± 0.00226  |

### η, 2 (5.0)
| p \ nTrk          | 1 (0.0,200.0)      | 2 (600.0)          |
|-------------------|--------------------|--------------------|
| 1 (3000.0,6000.0) | nan                | nan                |
| 2 (10000.0)       | 0.00000 ± 0.00000  | 0.00000 ± 0.00000  |
| 3 (15600.0)       | 0.01302 ± 0.00793  | -0.03060 ± 0.02227 |
| 4 (27000.0)       | -0.00070 ± 0.00317 | -0.00400 ± 0.00616 |
| 5 (60000.0)       | 0.00202 ± 0.00181  | 0.01276 ± 0.00408  |
| 6 (100000.0)      | 0.00149 ± 0.00207  | -0.00006 ± 0.00362 |


## `p -> fake`
### η, 1 (1.7,3.6)
| p \ nTrk          | 1 (0.0,200.0)     | 2 (600.0)         |
|-------------------|-------------------|-------------------|
| 1 (3000.0,6000.0) | 0.84912 ± 0.00702 | 0.85378 ± 0.01725 |
| 2 (10000.0)       | 0.94476 ± 0.00308 | 0.93468 ± 0.00672 |
| 3 (15600.0)       | 0.97323 ± 0.00187 | 0.96462 ± 0.00409 |
| 4 (27000.0)       | 0.98934 ± 0.00109 | 0.98129 ± 0.00236 |
| 5 (60000.0)       | 0.99467 ± 0.00071 | 0.99263 ± 0.00145 |
| 6 (100000.0)      | 0.99883 ± 0.00092 | 0.99254 ± 0.00265 |

### η, 2 (5.0)
| p \ nTrk          | 1 (0.0,200.0)     | 2 (600.0)          |
|-------------------|-------------------|--------------------|
| 1 (3000.0,6000.0) | nan               | nan                |
| 2 (10000.0)       | 0.93096 ± 0.06929 | -1.05930 ± 8.99634 |
| 3 (15600.0)       | 0.95483 ± 0.01117 | 1.03011 ± 0.03124  |
| 4 (27000.0)       | 0.99118 ± 0.00423 | 0.97725 ± 0.01008  |
| 5 (60000.0)       | 0.99191 ± 0.00221 | 0.98327 ± 0.00477  |
| 6 (100000.0)      | 0.99620 ± 0.00230 | 0.99700 ± 0.00460  |

Edit: Display more digits

**Comment by manuelfs** [comment]
It is not clear what the problem was. Can you include how you used to pass arguments, and how they are supposed to be passed?

Also, when there are some small efficiencies, can print the table with more decimals?

**Comment by yipengsun** [comment]
Efficiency precision updated in the original post.

**Comment by yipengsun** [comment]
I'm using Phoebe's method to shift all means of measured efficiencies, with the following algorithm (attached as a pdf):
[shift_mean.pdf](https://github.com/umd-lhcb/misid-unfold/files/8475174/shift_mean.pdf)

Some shifted values are: (for each element, 4 lines, first two nominator and denominator mean and std, before shift, last two AFTER):

```
=====
-0.014382322516224276 0.0131110666307553
1.0960643050989298 0.028665315968837868
0.005147928186391969 0.0131110666307553
0.9946292235078027 0.028665315968837868
0.005175725853134039

=====
-0.0010974147535493454 0.006398399155816239
0.8537777204152418 0.017248454710235797
0.0039312645605871135 0.006398399155816239
0.8537777204152418 0.017248454710235797
0.004604552761900499

=====
-0.0006604517792810409 0.0014437264774660459
0.9447632488626198 0.0030795678457630183
0.0007644284384222244 0.0014437264774660459
0.9447632488626198 0.0030795678457630183
0.000809121691960926

=====
-0.00031731870726269483 0.0010359865649657068
0.9732284676222152 0.001869110395700853
0.000592762749105537 0.0010359865649657068
0.9732284676222152 0.001869110395700853
0.0006090684446929206
```

**Comment by yipengsun** [comment]
And here's the updated unfolding result:

## Before unfolding (tagged yields)

![D0_tag_eta](https://user-images.githubusercontent.com/33738176/163031408-123616f7-1f34-45d0-9cd9-47487070fb81.png)
![D0_tag_ntracks](https://user-images.githubusercontent.com/33738176/163031411-8ef8f498-7fa0-4478-b499-51abd14d6658.png)
![D0_tag_p](https://user-images.githubusercontent.com/33738176/163031412-d4d2f7da-22fd-4c74-a8b9-96738075b9ea.png)


## After unfolding (true yields)
![D0_true_eta](https://user-images.githubusercontent.com/33738176/163031475-db1b9a52-1fcd-4abb-8135-89e407f66925.png)
![D0_true_ntracks](https://user-images.githubusercontent.com/33738176/163031480-89459c15-fba3-4116-b944-c15db7ad5998.png)
![D0_true_p](https://user-images.githubusercontent.com/33738176/163031482-5885e7bb-b2d2-4fc8-ad4c-142e794bc8bd.png)


For a single `P-ETA-nTracks` bin, the `true -> tag` response matrix looks like this:

https://github.com/umd-lhcb/misid-unfold/blob/004efb5f1af2944a24620b0e9db896e16781b3b0/histos/rdx-22_04_12_14_34-unfolded-2016/stdout.log#L3832-L3837

The unfolded `tag -> true` matrix looks like this:

https://github.com/umd-lhcb/misid-unfold/blob/004efb5f1af2944a24620b0e9db896e16781b3b0/histos/rdx-22_04_12_14_34-unfolded-2016/stdout.log#L3838-L3843

**Comment by yipengsun** [comment]
For one bin only, the response matrix is still very bad:

```
The raw true -> tag matrix is (row: fixed tag; col: fixed true):
  0.7279  0.1431  0.2033  0.5029  0.2055
  0.0115  0.1135  0.0697 -0.0000  0.0007
  0.0012  0.0031  0.0058  0.0844  0.0000
  0.0051  0.0039  0.0071  0.4980  0.0111
  0.2542  0.7364  0.7140  0.5040  0.7794
The fixed true -> tag matrix is (row: fixed tag; col: fixed true):
  0.7279  0.1431  0.2033  0.5029  0.2055
  0.0115  0.1135  0.0697 -0.0000  0.0007
  0.0012  0.0031  0.0058  0.0844  0.0000
  0.0051  0.0039  0.0071  0.4980  0.0111
  0.2542  0.7364  0.7140 -0.0853  0.7827
```

Puzzled on why the `pidcalib` raw efficiencies of `eTrue -> _Tag` would be `0.5029, 0, 0.0844, 0.4980, 0.5040`.

**Comment by yipengsun** [comment]
Hmm, from the raw efficiencies, the output is `2.22116 ± 8.56259`, which then get shifted to `0.5029`.

**Comment by yipengsun** [comment]
Found a good UMD notes on error propagation for weighted average: http://www.physics.umd.edu/courses/Phys261/F06/ErrorPropagation.pdf

I'll do error based on the equations listed at the bottom of page 4.

**Comment by yipengsun** [comment]
@manuelfs I might just found the culprit about the unreasonable transfer factors:

The transfer factors are `sum(tag -> true, true -> mu)`, but I incorrectly set the initial value to be at **1** INSTEAD OF **0**!

After the fix, the transfer factor matrix for `piTag -> muTag` looks like this (the uncertainties are FAKE, they are the default Poisson uncertainties)

```
## z ∈ [0.00, 200.00)

╒════════════╤═════════════════╤═════════════════╕
│ x / y      │ 1.70            │ 3.60            │
│            │ 3.60            │ 5.00            │
╞════════════╪═════════════════╪═════════════════╡
│ 3,000.00   │ 0.0016 ± 0.0397 │ 0.0056 ± 0.0750 │
│ 6,000.00   │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 6,000.00   │ 0.0067 ± 0.0818 │ 0.0074 ± 0.0859 │
│ 10,000.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 10,000.00  │ 0.0091 ± 0.0955 │ 0.0064 ± 0.0798 │
│ 15,600.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 15,600.00  │ 0.0096 ± 0.0980 │ 0.0060 ± 0.0777 │
│ 27,000.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 27,000.00  │ 0.0063 ± 0.0795 │ 0.0064 ± 0.0797 │
│ 60,000.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 60,000.00  │ 0.0023 ± 0.0479 │ 0.0040 ± 0.0630 │
│ 100,000.00 │                 │                 │
╘════════════╧═════════════════╧═════════════════╛


## z ∈ [200.00, 600.00)

╒════════════╤═════════════════╤═════════════════╕
│ x / y      │ 1.70            │ 3.60            │
│            │ 3.60            │ 5.00            │
╞════════════╪═════════════════╪═════════════════╡
│ 3,000.00   │ 0.0032 ± 0.0566 │ 0.0106 ± 0.1028 │
│ 6,000.00   │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 6,000.00   │ 0.0096 ± 0.0981 │ 0.0130 ± 0.1140 │
│ 10,000.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 10,000.00  │ 0.0101 ± 0.1007 │ 0.0100 ± 0.1002 │
│ 15,600.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 15,600.00  │ 0.0094 ± 0.0968 │ 0.0083 ± 0.0913 │
│ 27,000.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 27,000.00  │ 0.0069 ± 0.0833 │ 0.0064 ± 0.0803 │
│ 60,000.00  │                 │                 │
├────────────┼─────────────────┼─────────────────┤
│ 60,000.00  │ 0.0036 ± 0.0596 │ 0.0046 ± 0.0681 │
│ 100,000.00 │                 │                 │
╘════════════╧═════════════════╧═════════════════╛
```

At least they are all very small, which is consistent w/ what we expect.
