### ISSUE TITLE
Prepare misID weights for D* comb bkg

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/misid-unfold#7]
Currently we only have the weights for B comb. bkg. as the unfolding weights are different between nominal and B USB region.

For `D*`, we need to have different weights for events IN and OUTSIDE the `deltaM = (mD* -mD0)` window only.

So we need 2 species, let's call them `dst_nominal` and `dst_out`. The selections are:

- Both: All `B0` selections (so NO `B0` USB)
- Both: `D0` mass window cut to ensure we have a valid `D0` meson
- `dst_nominal`: `deltaM` within a given range. This means that for every event like this a REAL `D*` is likely present
- `dst_out`: `deltaM` outside the given range. This means that for these events it's likely a FAKE `D*` (which is just a true `D0` combined with some random slow `Pi`)

@Svende @manuelfs Do you think the cuts listed above are the cuts for the `D*` comb. bkg? If so, I'll start processing them and the ntuples containing the `D*` misID weights should be ready by next Mon.

**Comment by yipengsun** [comment]
Or, should we forget about the mass window cut on the `B0` entirely? Because that cuts would highly favor events within the `deltaM` window.

**Comment by Svende** [comment]
Yes I think we don't need the B mass window cut but apply the D0 mass window cut for those weights. So essentially we need what you call `dst_nominal` & `dst_out` selections.

**Comment by yipengsun** [comment]
In the end, we'll do the following:

- Apply the `D0` mass window cut to ensure we have a good `D0`
- Separate samples into 2 categories:
    - One inside the `deltaM` window
    - One outside
- Do unfolding separately
- Apply NO additional cut

**Comment by yipengsun** [comment]
OK, I started the misID ntuple generation process. Should be done before tomorrow afternoon.

**Comment by yipengsun** [comment]
Latest misID ntuples added at `rdx-run2-analysis`:

```
ntuples/0.9.6-2016_production/Dst_D0-mu_misid
```

Use `git-annex` to download these ntuples.

**Comment by yipengsun** [comment]
Testing if we can apply `b_m_ok && in_fit_range` for D* samples.

Currently, we only require `d0_m_ok && dst_m_ok` (`comb_d`) and `d0_m_ok && !dst_m_ok` (`comb_dsb`). For the D* right sign sample, we have:

- `comb_d`, tagged Pi: 396482
- `comb_dsb`, tagged Pi: 123218
- `comb_d`, tagged e: 60410
- `comb_dsb`, tagged e: 12001

For the wrong-sign Pi sample (I believe for this samples, more events will **FAIL** the `dst_m_ok` cut):

- `comb_d`, tagged Pi: 24364
- `comb_dsb`, tagged Pi:  110253
- `comb_d`, tagged e: 2185 (**this is already on the small side**)
- `comb_dsb`, tagged e: 9908 

Now if we require `b_m_ok && in_fit_range` _in addition_, for the same D* right sign sample:

- `comb_d`, tagged Pi: 385774
- `comb_dsb`, tagged Pi: 119803
- `comb_d`, tagged e: 59397
- `comb_dsb`, tagged e: 11708

For the wrong-sign Pi samples:

- `comb_dsb`, tagged, e: 23704
- `comb_dsb`, tagged Pi:  107239
- `comb_d`, tagged e: 2120
- `comb_dsb`: tagged e: 9672

To conclude, I believe it is fine to apply the additional `b_m_ok && in_fit_range` cuts.

FYI @manuelfs @Svende

**Comment by Svende** [comment]
Thanks for looking into this @yipengsun! Following your conclusion that those cuts won't kill too many events, are you then planning to do another round of unfolding misID tuples adding those cuts?

**Comment by yipengsun** [comment]
I plan to add those after we finish the preliminary fit for both comb D* and comb B. Because:

1. These cuts don't make a huge difference, so current weights are usable
2. There might be problems/bugs, but we can't tell until we do fit at least once. I'd like to use this opportunity to fix them together.

**Comment by yipengsun** [comment]
We've discussed to split the reweighting in 4 regions. For one of the region (`D` SB `B` SB), some of the tagged species contain very few events (namely, the electron sample contains only ~30 events).

**Comment by yipengsun** [comment]
Looking at the unfolding result in the `D` SB `B` SB region: (top: before, bot: after):

![Dst_dsb_bsb-tag_p](https://user-images.githubusercontent.com/33738176/175469819-d4e7e50a-a934-41c3-8828-ec7e3acd2dd7.png)
![Dst_dsb_bsb-true_p](https://user-images.githubusercontent.com/33738176/175469821-3b49a342-16b3-4559-808f-24047d24d753.png)

I think the unfolding is still working, in the sense that we still recovered some _true_ particles from the _tagged ghost_ samples.

So, I'll proceed with the current split, which has 4 separate unfolding regions.
